### PR TITLE
Create fundamentals category

### PR DESCRIPTION
**Pull request by gdestuynder**
Add Security Principles (for services) as fundamental.

Next step: move Security/Fundamentals.mediawiki to Security/Fundamentals/Rationales.mediawiki and redirect from Security/Fundamentals.mediawiki. 

Pre-review: @gene1wood made a pre-review of this document.

Sample / rendered page: https://wiki.mozilla.org/User:Gdestuynder/principles

### CODE REVIEW

**Comment by andrewkrug** [comment]
@kang I looked at this this morning and I thought it was a good start.

**Comment by jeffbryner** [comment]
Sorry for the delay, here's some feedback in no particular order: 

We should call out MFA requirement for servers that hold or process secrets (LDAP/OKTA/puppet) or have widespread access (nessus/service now).

Maybe include a 'do not' for TLS calling out some examples: http beyond load balancers, ldap using starttls, DB connections

Maybe include an inventory call out for ipv6?

**Comment by gdestuynder** [comment]
added commits for the 2 comments above before merging (but merged since review approved)

**Comment by gdestuynder** [comment]
pushed to https://wiki.mozilla.org/Security/Fundamentals/Security_Principles

**Pull request merged**
