### PR TITLE
More stable URL for the RRA template. Also updated to 2.5.1

### PR DESCRIPTION
**Pull request by gdestuynder**
Since I don't know if it's possible to have a reliable "Lastest RRA" link without comitting updates each time, this is a separately created template so that this one does not clutter our RRA drive or end up in the trash, basically a copy made specifically for our documentation. (which we should update from time to time)

### CODE REVIEW

**Comment by gene1wood** [comment]
What if we did this
* Create a folder in Google Drive called something like `RRA - Latest`
* Copy into that folder a single RRA revision and name it Latest or something
* When a new version comes up delete the old on in the folder and duplicate the new version, naming it Latest

Then in all the places we would link to the latest RRA template, we instead link to the folder and the user can always find the current RRA file in that folder.

**Comment by floatingatoll** [comment]
A slight variant of this approach works very well for Webops - linking to
the folder is key.

 - R.

**Comment by gdestuynder** [comment]
Reason I did not want to do that is that people are used to find the link in a specific, non-public drive location already. But that could be ok.

**Comment by gdestuynder** [comment]
repushing it separately as the URL currently is not functioning anyway. Feel free to open an issue or PR if you have a better fix

**Pull request closed without merging**
