### PR TITLE
capture desire to 2FA for select servers

### PR DESCRIPTION
**Pull request by jeffbryner**
Servers with secrets or widespread access should be 2FA'd on the server for any interactive access.

### CODE REVIEW

**Comment by gdestuynder** [comment]
@jeffbryner do you mean "direct 2FA call"? (as in, if you used MFA with SSO, it asks for MFA again directly with the MFA provider)
If so, I wonder if that goes more in line with a "2nd opinion" approach, where the 2nd opinion may be an access provider such as OIDC and/or "just MFA" for example

**Comment by floatingatoll** [comment]
+1 to rechecking against SSO at interactive login time, regardless of
future "2nd opinion" availability.

**Comment by jeffbryner** [comment]
Yes, special procedure for servers carrying secrets or with widespread access. 2nd opinion could potentially play; but wanted to capture current state.

**Comment by jeffbryner** [comment]
Yes, special procedure for servers carrying secrets or with widespread access. 2nd opinion could potentially play; but wanted to capture current state.

**Comment by gdestuynder** [comment]
@floatingatoll absolutely these things are not technology dependent. but this one also does not need to be protocol dependent either.

**Comment by gdestuynder** [comment]
@jeffbryner 
Made some changes that should change the meaning:
https://github.com/mozilla/wikimo_content/pull/115/files

Just looking for your r on that in addition to mine before merge

**Comment by gdestuynder** [comment]
This has been included in https://infosec.mozilla.org/fundamentals/security_principles#require-two-factor-authentication instead since the site has moved, and is already merged there. i think i forgot to close this basically, so closing ;-)

**Pull request closed without merging**
