### PR TITLE
Merge in more content from mana in order to move over the data classification to the public wiki

### PR DESCRIPTION
**Pull request by gdestuynder**

### CODE REVIEW

**Comment by gdestuynder** [comment]
@jeffbryner I'm wondering how we review these. Marshall + sv + you?

**Comment by jeffbryner** [comment]
r+

**Comment by gdestuynder** [comment]
All data from the internal wiki has been ported over to the public wiki.
You can find a rendered version here: https://wiki.mozilla.org/User:Gdestuynder/data

Please put feedback/comments on this issue though :)

**Comment by gdestuynder** [comment]
@jeffbryner Need re-r+ as I added everything left now (you only need to check the new commits though!)

**Comment by Phrozyn** [comment]
In the interest of helping others create standard documentation, it would be nice to include a reference to an example of how to properly fill out the data classification table seen in our standards and possibly link back to the examples of data classification.

**Comment by gdestuynder** [comment]
@phrozyn I agree though in this case I think this will go in the standard creation template (both backlink and how to fill the table)

**Comment by gdestuynder** [comment]
got r+ from marshall by email

**Pull request merged**
